"""add user

Revision ID: 5e7ee74e8096
Revises: fce7b8407028
Create Date: 2025-05-26 00:43:59.260076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e7ee74e8096"
down_revision: Union[str, None] = "fce7b8407028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.add_column("contact_book", sa.Column("user_id", sa.Integer(), nullable=False))
    op.alter_column(
        "contact_book", "info", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.create_foreign_key(
        None, "contact_book", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contact_book", type_="foreignkey")
    op.alter_column(
        "contact_book", "info", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.drop_column("contact_book", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
